[package]
name = "einrain_commands"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
einrain_utils = { path = "../einrain_utils" }
poise = "0.5.2"
serde = "1"
serde_json = "1"
lazy_static = "1.4.0"